InsureFlow360/force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <displayFormat>CLM-{00000}</displayFormat>
        <label>Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InsureFlow360/force-app/main/default/objects/Claim__c/fields/Claim_Amount__c.field-meta.xml
<CustomField>
    <fullName>Claim_Amount__c</fullName>
    <label>Claim Amount</label>
    <inlineHelpText>Enter the claim amount in the policy currency. Use numbers only.</inlineHelpText>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

InsureFlow360/force-app/main/default/objects/Claim__c/fields/Fraud_Score__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Score__c</fullName>
    <label>Fraud Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

InsureFlow360/force-app/main/default/objects/Claim__c/fields/Fraud_Status__c.field-meta.xml
<CustomField>
  <fullName>Fraud_Status__c</fullName>
  <label>Fraud Status</label>
  <inlineHelpText>Select the current Fraud Status.</inlineHelpText>
  <type>Picklist</type>
  <valueSet>
    <valueSetDefinition>
      <value>
        <fullName>Pending</fullName>
      </value>
      <value>
        <fullName>Low Risk</fullName>
      </value>
      <value>
        <fullName>Medium Risk</fullName>
      </value>
      <value>
        <fullName>High Risk</fullName>
      </value>
      <value>
        <fullName>Blocked</fullName>
      </value>
    </valueSetDefinition>
  </valueSet>
</CustomField>

InsureFlow360/force-app/main/default/objects/Claim__c/fields/Investigation_Required__c.field-meta.xml
<CustomField>
    <fullName>Investigation_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Investigation Required</label>
    <inlineHelpText>Check this box if Investigation Required.</inlineHelpText>
    <type>Checkbox</type>
</CustomField>

InsureFlow360/force-app/main/default/objects/Claim_Alert__e/Claim_Alert__e.object-meta.xml
<CustomObject>
    <label>Claim Alert</label>
    <pluralLabel>Claim Alerts</pluralLabel>
</CustomObject>

InsureFlow360/force-app/main/default/objects/Claim_Alert__e/fields/Alert_Type__c.field-meta.xml
<CustomField>
    <fullName>Alert_Type__c</fullName>
    <label>Alert Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

InsureFlow360/force-app/main/default/objects/Claim_Alert__e/fields/Claim_Id__c.field-meta.xml
<CustomField>
    <fullName>Claim_Id__c</fullName>
    <label>Claim Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

InsureFlow360/force-app/main/default/objects/Claim_Alert__e/fields/Fraud_Score__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Score__c</fullName>
    <label>Fraud Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

InsureFlow360/force-app/main/default/objects/Claim_Alert__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <inlineHelpText>Provide the Message details.</inlineHelpText>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

InsureFlow360/force-app/main/default/classes/FraudDetectionQueueable.cls
public with sharing class FraudDetectionQueueable implements Queueable {

    private List<Id> claimIds;

    public FraudDetectionQueueable(List<Id> claimIds) {
        this.claimIds = claimIds;
    }

    public void execute(QueueableContext context) {

        List<Claim__c> claims = [
            SELECT Id,
                   Name,
                   Claim_Amount__c,
                   Fraud_Score__c,
                   Fraud_Status__c,
                   Investigation_Required__c
            FROM Claim__c
            WHERE Id IN :claimIds
        ];

        List<Claim__c> claimsToUpdate = new List<Claim__c>();
        List<Claim_Alert__e> events = new List<Claim_Alert__e>();

        for (Claim__c claim : claims) {

            Integer fraudScore = calculateFraudScore(claim);

            claim.Fraud_Score__c = fraudScore;

            if (fraudScore >= 80) {

                claim.Fraud_Status__c = 'High Risk';
                claim.Investigation_Required__c = true;

                events.add(
                    new Claim_Alert__e(
                        Claim_Id__c = claim.Id,
                        Fraud_Score__c = fraudScore,
                        Alert_Type__c = 'HIGH_RISK',
                        Message__c = 'High risk claim detected'
                    )
                );

            } else if (fraudScore >= 50) {

                claim.Fraud_Status__c = 'Medium Risk';

            } else {

                claim.Fraud_Status__c = 'Low Risk';
            }

            claimsToUpdate.add(claim);
        }

        if (!claimsToUpdate.isEmpty()) {
            update claimsToUpdate;
        }

        if (!events.isEmpty()) {
            EventBus.publish(events);
        }

        IntegrationLogService.createInfoLog(
            'Fraud Engine',
            'Fraud analysis completed',
            null
        );
    }

    private Integer calculateFraudScore(Claim__c claim) {

        Integer score = 0;

        if (claim.Claim_Amount__c > 500000) {
            score += 60;
        }

        if (claim.Claim_Amount__c > 1000000) {
            score += 30;
        }

        return score;
    }
}