InsureFlow360/force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InsureFlow360/force-app/main/default/objects/Integration_Log__c/fields/Log_Level__c.field-meta.xml
<CustomField>
  <fullName>Log_Level__c</fullName>
  <label>Log Level</label>
  <inlineHelpText>Select the correct Log Level.</inlineHelpText>
  <type>Picklist</type>
  <valueSet>
    <valueSetDefinition>
      <value>
        <fullName>INFO</fullName>
      </value>
      <value>
        <fullName>WARN</fullName>
      </value>
      <value>
        <fullName>ERROR</fullName>
      </value>
      <value>
        <fullName>FATAL</fullName>
      </value>
    </valueSetDefinition>
  </valueSet>
</CustomField>

InsureFlow360/force-app/main/default/objects/Integration_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <inlineHelpText>Provide the Message details.</inlineHelpText>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

InsureFlow360/force-app/main/default/objects/Integration_Log__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <inlineHelpText>Enter the Source System.</inlineHelpText>
    <length>100</length>
    <type>Text</type>
</CustomField>

InsureFlow360/force-app/main/default/objects/Integration_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Retrying</fullName>
            </value>
            <value>
                <fullName>Partial Success</fullName>
            </value>
            <value>
                <fullName>Timeout</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

InsureFlow360/force-app/main/default/classes/IntegrationLogService.cls
public with sharing class IntegrationLogService {

    public static void createInfoLog(
        String source,
        String message,
        String relatedRecordId
    ) {

        insert new Integration_Log__c(
            Source_System__c = source,
            Message__c = message,
            Status__c = 'Success',
            Log_Level__c = 'INFO',
            Related_Record_Id__c = relatedRecordId
        );
    }

    public static void createErrorLog(
        String source,
        String message,
        String relatedRecordId
    ) {

        insert new Integration_Log__c(
            Source_System__c = source,
            Message__c = message,
            Status__c = 'Failed',
            Log_Level__c = 'ERROR',
            Related_Record_Id__c = relatedRecordId
        );
    }
}